services:
  # Services du backend
  php:
    container_name: challenge_php
    build:
      context: ./backend
      dockerfile: docker/php/Dockerfile
    networks:
      - challenge_network

  nginx:
    container_name: challenge_nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./backend/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - challenge_network

  # Service du frontend
  frontend:
    container_name: challenge_frontend
    build:
      context: ./frontend
      dockerfile: docker/Dockerfile
    ports:
      - '4200:80'
    networks:
      - challenge_network

networks:
  challenge_network:
    name: challenge_network
    # Supprimez cette ligne
    # external: true