services:
  # Services du backend
  php:
    container_name: challenge_php_dev
    build:
      context: ./backend
      dockerfile: docker/php/Dockerfile.dev
    volumes:
      - ./backend/symfony:/var/www/html
      - backend_vendor:/var/www/html/vendor
    networks:
      - challenge_network

  nginx:
    container_name: challenge_nginx_dev
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./backend/symfony:/var/www/html
      - ./backend/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - challenge_network

  # Service du frontend
  frontend:
    container_name: challenge_frontend_dev
    build:
      context: ./frontend
      dockerfile: docker/Dockerfile.dev
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - '4200:4200'
    networks:
      - challenge_network

# Ajoutez cette section à la fin du fichier
volumes:
  frontend_node_modules:
  backend_vendor:
networks:
  challenge_network:
    name: challenge_network_dev