services:
  php:
    container_name: challenge_php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./symfony:/var/www/html

  nginx:
    container_name: challenge_nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./symfony:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

